version: 2
config_ssh: &config_ssh
  name: Configure to clone repository with SSH connection
  command: |
    mkdir -p ~/.ssh
    ssh-keyscan -H github.com >> ~/.ssh/known_hosts
checkout_code: &checkout_code
  name: Checkout code (using shallow clone)
  command: |
    git config --global gc.auto 0 || true
    # Checkout
    git clone --depth=1 --branch ${CIRCLE_BRANCH} --single-branch ${CIRCLE_REPOSITORY_URL} .
    # Check the commit ID of the checked out code
    git reset --hard ${CIRCLE_SHA1}
jobs:
  build:
    docker:
    - image: circleci/ruby:2.7.2
    - image: circleci/mysql:5
    working_directory: ~/repo
    steps:
    - run:
        <<: *config_ssh
    - run:
        <<: *checkout_code
    - restore_cache:
        keys:
        - v3-dependencies-{{ checksum "Gemfile.lock" }}
        - v3-dependencies-
    - run:
        name: bundle install
        command: |
          gem update bundler
          bundle install --jobs=4 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
        - ./vendor/bundle
        key: v3-dependencies-{{ checksum "Gemfile.lock" }}
    - run:
        name: Setup databases
        command: bundle exec rake db:prepare
    - run:
        name: run tests
        command: bundle exec rspec
    environment:
    - RAILS_ENV: test
    - MYSQL_HOST: 127.0.0.1
workflows:
  version: 2
  build:
    jobs:
    - build
