version: 2.1

executors:
  ruby:
    parameters:
      version:
        type: string
    docker:
    - image: circleci/ruby:<< parameters.version >>
    - image: circleci/mysql:5
    environment:
    - RAILS_ENV: test
    - MYSQL_HOST: 127.0.0.1

jobs:
  rspec:
    parameters:
      version:
        type: string
    executor:
      name: ruby
      version: << parameters.version >>
    steps:
    - checkout
    - restore_cache:
        keys:
        - v3-dependencies-{{ checksum "Gemfile.lock" }}-<< parameters.version >>
    - run:
        name: bundle install
        command: |
          gem update bundler
          bundle config --local path vendor/bundle
          bundle install --jobs=4 --retry=3
    - save_cache:
        paths:
        - ./vendor/bundle
        key: v3-dependencies-{{ checksum "Gemfile.lock" }}
    - run:
        name: Setup databases
        command: bundle exec rake db:prepare
    - run:
        name: Run tests
        command: bundle exec rspec

workflows:
  version: 2
  rspecs:
    jobs:
    - rspec:
        matrix:
          parameters:
            version:
            - "2.7"
